# MongoDB server quick setup
# build or reload:
# UID_GID="$(id -u):$(id -g)" docker-compose up --detach --build

version: '3.7'

services: 
    # Data is recovered on first run
    mongo:
        image: mongo:latest
        volumes:
            # - ../dbdump/:/dbdump   # uncomment when restoring
            # - ./dbinit/:/docker-entrypoint-initdb.d  # uncomment when restoring
            - ../dbdata/:/data/db
            # - you_create_volume:/data/db  # uncomment on mac/win
        user: "${UID_GID}"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "10"

    jupyter:
        # `I just realized that my context (actual folder) was too big`
        # ref: https://github.com/docker/compose/issues/4396
        # build: 
        #     context: .
        #     dockerfile: jupyter.dockerfile
        image: 12f23eddde/jupyter-library-migration
        volumes:
            - ../:/app
        # jupyter will create config file in '/.local', where normal user have no permission
        # too tired to fix this
        # user: "${UID_GID}"
        ports:
            # note this setup allow arbitary code execution
            # for security concerns, better set to `127.0.0.1:8848:8848`
            - "8848:8888"
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "10"
        
